- hosts: localhost
  gather_facts: false
  vars:
    state: 'present'
    host: 'sandboxapicdc.cisco.com'
    username: '{{ ANSIBLE_NET_USERNAME }}'
    password: '{{ ANSIBLE_NET_PASSWORD }}'
    validate_certs: False
    tenant: 'TEST123'
    description: 'Description 123'
    vrf: 'VRF-TEST123'
    bd: 'BD-TEST'
    endpoint_move_detect: 'garp'
    enable_routing: False
  tasks:
    - name: Validate Input Specific
      assert:
        that:
          - tenant is string
          - description is string
          - vrf is string
          - bd is string
          - endpoint_move_detect is string

    - name: Ensure that ACI Tenant <'{{ tenant }}'> is in state <'{{ state }}'>
      aci_tenant:
        host: '{{ host }}'
        username: '{{ username }}'
        password: '{{ password }}'
        validate_certs: '{{ validate_certs }}'
        tenant: '{{ tenant}}'
        description: '{{ description }}'
        state: '{{ state }}'

    - name: Ensure that Vrf <'{{ vrf }}'> for Tenant <'{{ tenant }}'> is in state <'{{ state }}'>
      aci_vrf:
        host: '{{ host }}'
        username: '{{ username }}'
        password: '{{ password }}'
        validate_certs: '{{ validate_certs }}'
        vrf: '{{ vrf }}'
        tenant: '{{ tenant }}'
        descr: '{{ description }}'
        policy_control_preference: enforced
        policy_control_direction: ingress
        state: '{{ state }}'

    - name: Ensure that Bridge Domain <'{{ bd }}'> is in state <'{{ state }}'>
      aci_bd:
        host: '{{ host }}'
        username: '{{ username }}'
        password: '{{ password }}'
        validate_certs: '{{ validate_certs }}'
        tenant: '{{ tenant }}'
        vrf: '{{ vrf }}'
        bd: '{{ bd }}'
        endpoint_move_detect: '{{ endpoint_move_detect }}'
        enable_routing: '{{ enable_routing }}'
        description: '{{ description }}'
        state: '{{ state }}'